name: sudokats
description: "A Sudoku game with cute cat themes."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.6.0
  shared_preferences: ^2.5.3
  flutter_riverpod: ^3.0.3
  logger: ^2.6.2
  web: ^1.1.1
  package_info_plus: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  custom_lint: ^0.8.0
  riverpod_lint: ^3.0.3
  flutter_launcher_icons: ^0.9.2

flutter:
  uses-material-design: true

  assets:
    - assets/images/black_cat_1.png
    - assets/images/white_cat_1.png
    - assets/images/white_cat_2.png
    - assets/images/difficulty_easy.png
    - assets/images/difficulty_medium.png
    - assets/images/difficulty_hard.png
    - assets/images/difficulty_expert.png

flutter_icons:
  ios: true
  image_path: "iconkitchen/android/res/mipmap-mdpi/ic_launcher.png"
  image_path_ios: "iconkitchen/ios/AppIcon.appiconset/Icon-App-20x20@1x.png"
  android:
    file_name: "android/app/build.gradle.kts"
